export const ALL_PURCHASE_REQUEST = "ALL_PURCHASE_REQUEST";
export const ALL_PURCHASE_SUCCESS = "ALL_PURCHASE_SUCCESS";
export const ALL_PURCHASE_FAIL = "ALL_PURCHASE_FAIL";

export const ADMIN_PURCHASE_REQUEST = "ADMIN_PURCHASE_REQUEST";
export const ADMIN_PURCHASE_SUCCESS = "ADMIN_PURCHASE_SUCCESS";
export const ADMIN_PURCHASE_FAIL = "ADMIN_PURCHASE_FAIL";

export const NEW_PURCHASE_REQUEST = "NEW_PURCHASE_REQUEST";
export const NEW_PURCHASE_SUCCESS = "NEW_PURCHASE_SUCCESS";
export const NEW_PURCHASE_RESET = "NEW_PURCHASE_RESET";
export const NEW_PURCHASE_FAIL = "NEW_PURCHASE_FAIL";

export const DELETE_PURCHASE_REQUEST = "DELETE_PURCHASE_REQUEST";
export const DELETE_PURCHASE_SUCCESS = "DELETE_PURCHASE_SUCCESS";
export const DELETE_PURCHASE_RESET = "DELETE_PURCHASE_RESET";
export const DELETE_PURCHASE_FAIL = "DELETE_PURCHASE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
